Delivery_app.web/Controllers/PushNotificationController.cs
using Delivery_app.Entities;
using Delivery_app.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delivery_app.web.Models
{
    public class PushNotificationController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IToastNotification _toastNotification;
        private readonly INotificationService _notificationService;

        public PushNotificationController(AppDbContext context,
            IToastNotification toastNotification,
            INotificationService notificationService)
        {
            _context = context;
            _toastNotification = toastNotification;
            _notificationService = notificationService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                PushNotificationModel model = new PushNotificationModel();

                var users = await _context.users
                                    .Select(u => new SelectListItem
                                    {
                                        Value = u.user_id.ToString(),
                                        Text = u.name
                                    })
                                    .ToListAsync();

                model.userList.AddRange(users);

                return View(model);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Something went wrong, try again later.");

                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(PushNotificationModel model)
        {
            if (!ModelState.IsValid)
            {
                var users = await _context.users
                                    .Select(u => new SelectListItem
                                    {
                                        Value = u.user_id.ToString(),
                                        Text = u.name
                                    })
                                    .ToListAsync();

                model.userList.AddRange(users);

                return View(model);
            }

            try
            {
                // send notification to selected users
                List<Task> tasks = new List<Task>();

                foreach (var u in model.toUser)
                {
                    Task t = Task.Run(() => sendPushNotificationHandler(u, model.title, model.content));

                    tasks.Add(t);
                }

                Task.WaitAll(tasks.ToArray());

                _toastNotification.AddSuccessToastMessage("Push notification sent successfully.");

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Something went wrong, try again later.");

                return RedirectToAction("Index");
            }
        }

        private async Task sendPushNotificationHandler(string uid, string title, string content)
        {
            var user = await _context.users.FindAsync(int.Parse(uid));
            await _notificationService
                        .SendNotification(user.fcm_token, title, title, content);
        }
    }
}

Delivery_app.web/Views/PushNotification/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Notification";
}
@model PushNotificationModel

<div class="pb-3">
    <h3>Send Push Notification</h3>
</div>

<div>
    <form id="emailForm" class="py-2" asp-controller="PushNotification" asp-action="Index" method="post">
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">To Users<br><small>(Hold <kbd>ctrl</kbd> select multiple)</small></label>
            <div class="col-sm-6">
                <select class="form-control" multiple asp-for="@Model.toUser"
                        asp-items="@Model.userList">
                </select>
                <span asp-validation-for="@Model.toUser" class="text-danger small font-italic"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Notification Title</label>
            <div class="col-sm-6">
                <input asp-for="@Model.title" type="text" class="form-control" placeholder="Title of your push notification">
                <span asp-validation-for="@Model.title" class="text-danger small font-italic"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Notification Content</label>
            <div class="col-sm-6">
                <input asp-for="@Model.content" id="messageBody" type="text" class="form-control" placeholder="Content of your push notification">
                <span asp-validation-for="@Model.content" class="text-danger small font-italic"></span>
            </div>
        </div>
        <div class="py-2">
            <button class="btn btn-info" type="submit">
                <i class="far fa-paper-plane pr-1"></i>
                <span>Push</span>
            </button>
            <button class="btn btn-outline-secondary" type="reset">
                <i class="fas fa-redo pr-1"></i>
                <span>Reset</span>
            </button>
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(function () {
            $("#NotificationsLink").removeClass("text-dark");
            $("#NotificationsLink").addClass("text-danger");
        });
    </script>
}