Delivery_app.web/Controllers/PromotionController.cs
using AutoMapper;
using Delivery_app.Entities;
using Delivery_app.web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delivery_app.web.Controllers
{
    public class PromotionController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;

        public PromotionController(AppDbContext context, IMapper mapper, IToastNotification toastNotification)
        {
            _context = context;
            _mapper = mapper;
            _toastNotification = toastNotification;
        }

        public async Task<IActionResult> Index(string searchQuery)
        {
            try
            {
                var promoCodes = await _context.promo_codes
                                            .OrderByDescending(o => o.created_at)
                                            .ToListAsync();

                var promoCodesModel = _mapper.Map<List<PromoCodes>, List<PromoCodeModel>>(promoCodes);

                if (!String.IsNullOrEmpty(searchQuery))
                {
                    promoCodesModel = promoCodesModel.Where(o =>
                        o.name.Contains(searchQuery)
                        || o.description.Contains(searchQuery)
                        ).ToList();
                }

                return View(promoCodesModel);
            }
            catch(Exception)
            {
                _toastNotification.AddErrorToastMessage("Failed to fetch promo codes.");
                return View(null);
            }
        }

        public IActionResult Create()
        {
            return View(new PromoCodeModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(PromoCodeModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var promoCode = _mapper.Map<PromoCodes>(model);

                promoCode.created_at = DateTime.Now;
                promoCode.updated_at = DateTime.Now;

                _context.promo_codes.Add(promoCode);

                await _context.SaveChangesAsync();

                _toastNotification.AddSuccessToastMessage("Promo Code added successfully.");

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Error occured, try again later.");
                return View(model);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }

            var promoCode = await _context.promo_codes.FindAsync(id);

            if (promoCode == null)
            {
                _toastNotification.AddErrorToastMessage("No specified promo code found.");
                return RedirectToAction("Index");
            }

            var promoCodeModel = _mapper.Map<PromoCodeModel>(promoCode);

            return View(promoCodeModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, PromoCodeModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (id != model.promo_code_id)
            {
                ModelState.AddModelError("promo_code_id", "Id is not the same");
                return View(model);
            }

            try
            {
                if (id == 0)
                {
                    return RedirectToAction("Index");
                }

                var promoCode = await _context.promo_codes.FindAsync(id);

                if (promoCode == null)
                {
                    _toastNotification.AddErrorToastMessage("No found on this specified id.");
                    return RedirectToAction("Index");
                }

                var editPromoCode = _mapper.Map<PromoCodes>(model);

                // update fields
                promoCode.name = editPromoCode.name;
                promoCode.description = editPromoCode.description;
                promoCode.discount = editPromoCode.discount;
                promoCode.discount_type = editPromoCode.discount_type;
                promoCode.minimum_spend = editPromoCode.minimum_spend;
                promoCode.num_claim_per_user = editPromoCode.num_claim_per_user;
                promoCode.quantity = editPromoCode.quantity;
                promoCode.validity = editPromoCode.validity;
                promoCode.updated_at = DateTime.Now;

                _context.promo_codes.Update(promoCode);

                await _context.SaveChangesAsync();

                _toastNotification.AddInfoToastMessage("Edited successfully.");

                return RedirectToAction("Index");
            }
            catch(Exception)
            {
                _toastNotification.AddErrorToastMessage("Error occured, try again later.");
                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }

            var promoCode = await _context.promo_codes.FindAsync(id);

            if(promoCode == null)
            {
                _toastNotification.AddErrorToastMessage("No found on this specified id.");
                return RedirectToAction("Index");
            }

            _context.promo_codes.Remove(promoCode);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

    }
}

Delivery_app.web/Views/Promotion/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create new promo code";
}
@model PromoCodeModel

<div class="pb-3 pt-3">
    <a asp-controller="Promotion" asp-action="Index" class="text-decoration-none text-dark d-flex justify-content-start align-items-baseline">
        <i class="fas fa-chevron-left fa-sm"></i>
        <h6 class="pl-2">Back</h6>
    </a>
    <h3 class="pt-2 pl-2">Add promo code</h3>
</div>

<div class="px-2 pb-3">
    <form asp-action="Create" method="post">
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label>Promo Code Name</label>
                    <input asp-for="@Model.name" type="text" class="form-control" placeholder="Promo Code Name">
                    <span asp-validation-for="@Model.name" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label>Promo Code Description</label>
                    <input asp-for="@Model.description" type="text" class="form-control" placeholder="Promo Code Description">
                    <span asp-validation-for="@Model.description" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label class="pr-3">Promo Code Discount</label>
                    @foreach (var c in System.Enum.GetValues(typeof(DiscountType)).OfType<DiscountType>())
                    {
                        <div class="form-check form-check-inline">
                            <label class="form-check-input" asp-for="@Model.discount_type">@c</label>
                            <input class="form-check-label mb-2" type="radio" asp-for="@Model.discount_type" value="@((int)c)" checked="@(c == Model?.discount_type)" />
                        </div>
                    }
                    <input asp-for="@Model.discount" type="number" class="form-control" placeholder="Promo Code Discount">
                    <span asp-validation-for="@Model.discount" class="text-danger small font-italic"></span>
                    <span asp-validation-for="@Model.discount_type" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label>Minimum Spend</label>
                    <input asp-for="@Model.minimum_spend" type="number" class="form-control" placeholder="Minimum Spend">
                    <span asp-validation-for="@Model.minimum_spend" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label>Total Quantity</label>
                    <input asp-for="@Model.quantity" type="number" class="form-control" placeholder="Total Quantity">
                    <span asp-validation-for="@Model.quantity" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label>No. of Redeems Per User</label>
                    <input asp-for="@Model.num_claim_per_user" type="number" class="form-control" placeholder="No. of Redeems Per User">
                    <span asp-validation-for="@Model.num_claim_per_user" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label>Coupon Validitiy</label>
                    <input asp-for="@Model.validity" type="date" class="form-control" placeholder="Validitiy">
                    <span asp-validation-for="@Model.validity" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col"></div>
        </div>
        <div>
            <input class="btn btn-info" type="submit" name="Submit" value="Submit" />
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(function () {
            $("#PromotionsLink").removeClass("text-dark");
            $("#PromotionsLink").addClass("text-danger");
        });
    </script>
}

Delivery_app.web/Views/Promotion/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit promo code";
}
@model PromoCodeModel

<div class="pb-3 pt-3">
    <a asp-controller="Promotion" asp-action="Index" class="text-decoration-none text-dark d-flex justify-content-start align-items-baseline">
        <i class="fas fa-chevron-left fa-sm"></i>
        <h6 class="pl-2">Back</h6>
    </a>
    <h3 class="pt-2 pl-2">Edit promo code</h3>
</div>

<div class="px-2 pb-3">
    <form asp-action="Edit" method="post">
        <div class="form-group">
            <input type="hidden" asp-for="@Model.promo_code_id" />
            <span asp-validation-for="@Model.promo_code_id" class="text-danger small font-italic"></span>
        </div>
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label>Promo Code Name</label>
                    <input asp-for="@Model.name" type="text" class="form-control" placeholder="Promo Code Name">
                    <span asp-validation-for="@Model.name" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label>Promo Code Description</label>
                    <input asp-for="@Model.description" type="text" class="form-control" placeholder="Promo Code Description">
                    <span asp-validation-for="@Model.description" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label class="pr-3">Promo Code Discount</label>
                    @foreach (var c in System.Enum.GetValues(typeof(DiscountType)).OfType<DiscountType>())
                    {
                        <div class="form-check form-check-inline">
                            <label class="form-check-input" asp-for="@Model.discount_type">@c</label>
                            <input class="form-check-label mb-2" type="radio" asp-for="@Model.discount_type" value="@((int)c)" checked="@(c == Model?.discount_type)" />
                        </div>
                    }
                    <input asp-for="@Model.discount" type="number" class="form-control" placeholder="Promo Code Discount">
                    <span asp-validation-for="@Model.discount" class="text-danger small font-italic"></span>
                    <span asp-validation-for="@Model.discount_type" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label>Minimum Spend</label>
                    <input asp-for="@Model.minimum_spend" type="number" class="form-control" placeholder="Minimum Spend">
                    <span asp-validation-for="@Model.minimum_spend" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label>Total Quantity</label>
                    <input asp-for="@Model.quantity" type="number" class="form-control" placeholder="Total Quantity">
                    <span asp-validation-for="@Model.quantity" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label>No. of Redeems Per User</label>
                    <input asp-for="@Model.num_claim_per_user" type="number" class="form-control" placeholder="No. of Redeems Per User">
                    <span asp-validation-for="@Model.num_claim_per_user" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col">
                <div class="form-group">
                    <label>Coupon Validitiy</label>
                    <input asp-for="@Model.validity" type="date" class="form-control" placeholder="Validitiy">
                    <span asp-validation-for="@Model.validity" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col"></div>
        </div>
        <div>
            <input class="btn btn-info" type="submit" name="Edit" value="Edit" />
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(function () {
            $("#PromotionsLink").removeClass("text-dark");
            $("#PromotionsLink").addClass("text-danger");
        });
    </script>
}

Delivery_app.web/Views/Promotion/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Promotions";
}
@model IEnumerable<PromoCodeModel>

<div class="pb-3">
    <h3>Promo Codes</h3>
</div>
<div class="d-flex justify-content-between pb-3 flex-column flex-sm-row">
    <form asp-controller="Promotion" asp-action="Index" class="shadow-sm">
        <div class="input-group">
            <input class="form-control" type="search" name="searchQuery" placeholder="Search.." aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-info" type="submit">Search</button>
            </div>
        </div>
    </form>
    <div class="shadow-sm pt-3 pt-sm-0">
        <a asp-controller="Promotion" asp-action="Create" class="btn btn-success">
            <i class="fas fa-plus pr-2"></i>Promo Code
        </a>
    </div>
</div>

<div>
    <div class="d-flex w-100 flex-wrap justify-content-center justify-content-md-start">
        @foreach (var p in Model)
        {
            <div class="card shadow promo-code-width mr-4 mb-4">
                <div class="px-3 pt-3">
                    <div class="d-flex justify-content-between">
                        <a asp-action="Edit" asp-route-id="@p.promo_code_id" class="text-decoration-none text-dark">
                            <i class="fas fa-edit"></i>
                        </a>
                        <form asp-action="Delete" asp-route-id="@p.promo_code_id" method="post">
                            <button type="submit" style="all: unset;cursor: pointer;">
                                <i class="far fa-trash-alt"></i>
                            </button>
                        </form>
                    </div>
                    <div class="py-2 d-flex flex-column align-items-center">
                        <p class="text-muted">@p.description</p>
                        <h4 class="text-uppercase">@p.name</h4>
                        <p class="text-muted">@($"Expiry Date - {string.Format("{0:dd/MM/yyyy}", p.validity)}")</p>
                    </div>
                    <div class="py-2">
                        <ul>
                            @if (p.discount_type == DiscountType.Percent)
                            {
                                <li>@($"Discount {p.discount}%")</li>
                            }
                            else
                            {
                                <li>@($"Discount RM{p.discount}")</li>
                            }
                            <li>@($"Min order amount is RM{p.minimum_spend}")</li>
                            <li>@($"Quantity {p.quantity} left")</li>
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts{
    <script>
        $(function () {
            $("#PromotionsLink").removeClass("text-dark");
            $("#PromotionsLink").addClass("text-danger");
        });
    </script>
}