Delivery_app.web/Controllers/EmailController.cs
using Delivery_app.Entities;
using Delivery_app.web.Models;
using Delivery_app.web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delivery_app.web.Controllers
{
    public class EmailController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IToastNotification _toastNotification;
        private readonly IEmailService _emailService;

        public EmailController(AppDbContext context, 
            IToastNotification toastNotification,
            IEmailService emailService)
        {
            _context = context;
            _toastNotification = toastNotification;
            _emailService = emailService;
        }

        public async Task<IActionResult> Index()
        {
            EmailModel model = new EmailModel();

            var userGroup = new SelectListGroup { Name = "Users" };
            var courierGroup = new SelectListGroup { Name = "Couriers" };

            var userEmail = await _context.users
                                .Where(u => u.email != null)
                                .Select(u => new SelectListItem
                                    {
                                        Value = u.email,
                                        Text = u.email,
                                        Group = userGroup
                                    })
                                .ToListAsync();

            var courierEmail = await _context.couriers
                                .Where(c => c.email != null)
                                .Select(c => new SelectListItem
                                {
                                    Value = c.email,
                                    Text = c.email,
                                    Group = courierGroup
                                })
                                .ToListAsync();

            model.emailList.AddRange(userEmail);
            model.emailList.AddRange(courierEmail);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(EmailModel model)
        {
            if (!ModelState.IsValid)
            {
                var userGroup = new SelectListGroup { Name = "Users" };
                var courierGroup = new SelectListGroup { Name = "Couriers" };

                var userEmail = await _context.users
                                    .Where(u => u.email != null)
                                    .Select(u => new SelectListItem
                                    {
                                        Value = u.email,
                                        Text = u.email,
                                        Group = userGroup
                                    })
                                    .ToListAsync();

                var courierEmail = await _context.couriers
                                    .Where(c => c.email != null)
                                    .Select(c => new SelectListItem
                                    {
                                        Value = c.email,
                                        Text = c.email,
                                        Group = courierGroup
                                    })
                                    .ToListAsync();

                model.emailList.AddRange(userEmail);
                model.emailList.AddRange(courierEmail);

                return View(model);
            }

            try
            {
                // send email to selected emails
                await _emailService.SendEmailAsync(
                        "Hi",
                        model.toEmail,
                        model.subject,
                        model.body
                    );

                _toastNotification.AddSuccessToastMessage("Email sent successfully.");

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Something went wrong, try again later.");

                return RedirectToAction("Index");
            }
        }
    }
}

Delivery_app.web/Controllers/MainController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using NToastNotify;
using Delivery_app.Entities;
using Delivery_app.web.Models;
using Microsoft.EntityFrameworkCore;

namespace Delivery_app.web.Controllers
{
    [Authorize]
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly AppDbContext _context;

        public MainController(ILogger<MainController> logger, 
            IToastNotification toastNotification,
            AppDbContext context)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _context = context;
        }

        public async Task<IActionResult> Index(DashboardViewModel model)
        {
            try
            {
                IQueryable<Orders> orders = _context.orders;
                model.totalOrdersCount = await orders.CountAsync();

                IQueryable<Users> users = _context.users;
                model.totalUsersCount = await users.CountAsync();

                IQueryable<Couriers> couriers = _context.couriers;
                model.totalCouriersCount = await couriers.CountAsync();

                model.totalPayments = Convert.ToInt32(await _context.payments.SumAsync(p => p.amount));

                return View(model);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Failed to load the display data.");

                return View(new DashboardViewModel());
            }
        }

        public async Task<IActionResult> MonthlyOrders()
        {
            try
            {
                var date = DateTime.Now;

                var monthlydata = await _context.orders
                                    .Where(o => o.created_at.Month == date.Month)
                                    .GroupBy(g => new { g.created_at.Day })
                                    .Select(o =>
                                        new
                                        {
                                            day = o.Key.Day,
                                            count = o.Count()
                                        }
                                    )
                                    .ToListAsync();

                return Ok(monthlydata);
            }
            catch (Exception e)
            {
                return StatusCode(500, new { message = e.Message });
            }
        }
    }
}

Delivery_app.web/Controllers/OrderController.cs
using AutoMapper;
using Delivery_app.Entities;
using Delivery_app.web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delivery_app.web.Controllers
{
    public class OrderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;

        public OrderController(AppDbContext context, IMapper mapper, IToastNotification toastNotification)
        {
            _context = context;
            _mapper = mapper;
            _toastNotification = toastNotification;
        }

        public async Task<IActionResult> Index(string searchQuery)
        {
            var orders = await _context.orders
                                    .OrderByDescending(o => o.created_at)
                                    .ToListAsync();

            var orderViewModel = _mapper.Map<List<Orders>, List <OrderViewModel>>(orders);

            if (!String.IsNullOrEmpty(searchQuery))
            {
                orderViewModel = orderViewModel.Where(o =>
                    o.name.Contains(searchQuery)
                    || o.contact_num.Contains(searchQuery)
                    || o.pick_up_address.Contains(searchQuery)
                    ).ToList();
            }

            return View(orderViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CancelOrder(int id)
        {
            try
            {
                var order = await _context.orders.FindAsync(id);

                if (order == null)
                {
                    _toastNotification.AddErrorToastMessage($"Order no found.");
                    return RedirectToAction("Index");
                }

                if (order.delivery_status != DeliveryStatus.Assigned)
                {                    
                    _toastNotification.AddErrorToastMessage($"In delivery or completed order cannot be cancel.");
                    return RedirectToAction("Index");
                }

                // othherwise set order cancelled
                order.delivery_status = DeliveryStatus.Cancelled;

                _context.orders.Update(order);
                await _context.SaveChangesAsync();

                _toastNotification.AddInfoToastMessage("Cancelled order successfully.");

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage($"Error occured, try again later.");
                return RedirectToAction("Index");
            }
        }
    }
}

Delivery_app.web/Controllers/UserController.cs
using AutoMapper;
using Delivery_app.Entities;
using Delivery_app.Services;
using Delivery_app.web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delivery_app.web.Controllers
{
    public class UserController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;

        public UserController(AppDbContext context, IMapper mapper, IToastNotification toastNotification)
        {
            _context = context;
            _mapper = mapper;
            _toastNotification = toastNotification;
        }

        public async Task<IActionResult> Index(string searchQuery)
        {
            var users = await _context.users.ToListAsync();

            var userViewModel = _mapper.Map<List<Users>, List<UserViewModel>>(users);

            if (!String.IsNullOrEmpty(searchQuery))
            {
                userViewModel = userViewModel.Where(u =>
                    u.name.Contains(searchQuery)
                    || u.phone_num.ToString().Contains(searchQuery)
                    ).ToList();
            }

            return View(userViewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var user = await _context.users.FindAsync(id);

                if (user == null)
                {
                    _toastNotification.AddErrorToastMessage($"Failed to fetch edit user.");
                    return RedirectToAction("Index");
                }

                var userViewModel = _mapper.Map<UserViewModel>(user);

                return View(userViewModel);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage($"Error occured, try again later.");
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, UserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (id != model.user_id)
            {
                ModelState.AddModelError("user_id", "Id is not the same");
                return View(model);
            }

            var user = await _context.users.FindAsync(id);

            if (user == null)
            {
                _toastNotification.AddErrorToastMessage($"Failed to edit.");
                return View(model);
            }

            var editUser = _mapper.Map<Users>(model);

            // update fields
            user.name = editUser.name;
            user.phone_num = editUser.phone_num;
            user.email = editUser.email;
            user.locked = editUser.locked;
            user.updated_at = DateTime.Now;

            _context.users.Update(user);

            await _context.SaveChangesAsync();

            _toastNotification.AddInfoToastMessage("Edited successfully.");

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ResetPassword(int id)
        {
            try
            {
                ResetPasswordModel model = new ResetPasswordModel();

                var user = await _context.users.FindAsync(id);

                if (user == null)
                {
                    _toastNotification.AddErrorToastMessage($"Failed to fetch user.");
                    return RedirectToAction("Index");
                }

                model.id = user.user_id;

                return View(model);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage($"Error occured, try again later.");
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(int id, ResetPasswordModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if (id != model.id)
                {
                    ModelState.AddModelError("id", "Id is not the same");
                    return View(model);
                }

                var user = await _context.users.FindAsync(model.id);

                if (user == null)
                {
                    _toastNotification.AddErrorToastMessage($"Failed to fetch user.");
                    return View(model);
                }

                byte[] passwordHash, passwordSalt;

                AccountService.CreatePasswordHash(model.new_password, out passwordHash, out passwordSalt);

                user.password = Convert.ToBase64String(passwordHash);
                user.password_salt = Convert.ToBase64String(passwordSalt);

                _context.users.Update(user);
                await _context.SaveChangesAsync();

                _toastNotification.AddInfoToastMessage("Edited successfully.");

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage($"Error occured, try again later.");
                return View(model);
            }
        }
    }
}

Delivery_app.web/Views/Shared/_AccountLayout.cshtml
@using Delivery_app
@using Delivery_app.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body style="background-color:lightslategrey">
    <div class="row d-flex justify-content-center align-items-center min-vh-100 w-100">
        <div class="card shadow px-3 py-4 rounded-0 col-8 col-md-6 col-lg-5 col-xl-3">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Delivery_app.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Delivery App</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Alata&family=Roboto+Condensed&display=swap" rel="stylesheet">
    @RenderSection("Heads", required: false)
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <nav class="navbar navbar-expand navbar-toggleable navbar-dark my-shadow px-4" style="background-color: #D50000;">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-controller="Main" asp-action="Index">
                        <img width="116" height="35" src="~/img/cover2-crop.png">
                    </a>
                    <div class="navbar-collapse collapse">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <ul class="navbar-nav ml-auto pr-md-2 pr-0">
                                <li class="nav-item">
                                    <span class="nav-link text-light d-flex align-items-center">
                                        <img class="rounded-circle img-fluid mr-2" width="28" src="https://stregasystem.com/img/users/user.png" alt="profile" />
                                        <span class="d-none d-md-block">@User.Identity.Name</span>
                                    </span>
                                </li>
                            </ul>
                            <form class="form-inline text-white pr-2 pr-md-0">
                                <a asp-controller="Account" asp-action="Logout" class="btn btn-light rounded-0 btn-sm my-2 my-sm-0" type="submit">Logout</a>
                            </form>
                        }
                    </div>
                    <button class="navbar-toggler d-block d-md-none" id="burger-menu" type="button" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </nav>
        </header>

        <nav class="nav d-none d-md-flex" id="nav">
            <div style="position: relative;overflow: hidden;width: auto;height: 100%;">
                <div class="w-100 d-flex flex-column pt-4 h-100">
                    <div class="px-4">
                        <a asp-controller="Main" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="DashboardLink">
                            <span class="nav-icon">
                                <i class="fas fa-chart-bar"></i>
                            </span>
                            <span class="nav-text">Dashboard</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="Courier" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="CouriersLink">
                            <span class="nav-icon">
                                <i class="fas fa-people-carry"></i>
                            </span>
                            <span class="nav-text">Couriers</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="Order" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="OrdersLink">
                            <span class="nav-icon">
                                <i class="fas fa-box-open"></i>
                            </span>
                            <span class="nav-text">Orders</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="User" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="UsersLink">
                            <span class="nav-icon">
                                <i class="fas fa-users"></i>
                            </span>
                            <span class="nav-text">Users</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="Promotion" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="PromotionsLink">
                            <span class="nav-icon">
                                <i class="fas fa-bullhorn"></i>
                            </span>
                            <span class="nav-text">Promotions</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="Email" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="EmailsLink">
                            <span class="nav-icon">
                                <i class="far fa-paper-plane"></i>
                            </span>
                            <span class="nav-text">Emails</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="PushNotification" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="NotificationsLink">
                            <span class="nav-icon">
                                <i class="far fa-bell"></i>
                            </span>
                            <span class="nav-text">Notifications</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="Report" asp-action="UserReport" class="d-flex px-1 py-2 text-decoration-none text-dark" id="ReportLink">
                            <span class="nav-icon">
                                <i class="far fa-file-alt"></i>
                            </span>
                            <span class="nav-text">Reports</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="Payment" asp-action="OrderStatement" class="d-flex px-1 py-2 text-decoration-none text-dark" id="PaymentLink">
                            <span class="nav-icon">
                                <i class="fas fa-money-check"></i>
                            </span>
                            <span class="nav-text">Payments</span>
                        </a>
                    </div>
                    <div class="px-4">
                        <a asp-controller="Setting" asp-action="Index" class="d-flex px-1 py-2 text-decoration-none text-dark" id="SettingsLink">
                            <span class="nav-icon">
                                <i class="fas fa-sliders-h"></i>
                            </span>
                            <span class="nav-text">Settings</span>
                        </a>
                    </div>
                </div>
            </div>
        </nav>

        <main role="main" class="pb-3 main">
            <div class="px-4 py-3 card rounded-0">
                @RenderBody()
            </div>
        </main>

        <!-- loading overlay -->
        <div id="overlay" style="display: none;">
            <div class="spinner"></div>
            <br />
            <span class="lead">Loading...</span>
        </div>

    </div>
    <!-- scripts -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        document.addEventListener("submit", function (e) {
            $('#overlay').hide().fadeIn();
        });
        document.querySelector("#burger-menu").addEventListener("click", function (e) {
            let isdnone = document.querySelector("#nav").classList.contains("d-none");
            if (isdnone) {
                document.querySelector("#nav").classList.remove("d-none");
            } else {
                document.querySelector("#nav").classList.add("d-none");
            }
        })
    </script>
    <!-- add ntoast -->
    @await Component.InvokeAsync("NToastNotify")
    @RenderSection("Scripts", required: false)
</body>

</html>