Delivery_app.web/Models/CourierViewModel.cs
using Delivery_app.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Delivery_app.web.Models
{
    public class CourierViewModel
    {
        public CourierViewModel()
        {
            this.documents = new List<Documents>();
        }

        public int courier_id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string phone_num { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string vehicle_plate_no { get; set; }
        public string profile_picture { get; set; }
        public ICollection<Documents> documents { get; set; }
        [Required]
        public VehicleType vehicle_type { get; set; }
        [Required]
        public double commission { get; set; }
        [Required]
        public bool disable { get; set; }
        public DateTime created_at { get; set; }
        public DateTime updated_at { get; set; }
        public bool isRegistered { get; set; } = false;
    }
}

Delivery_app.web/Controllers/CourierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Delivery_app.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Delivery_app.web.Settings;
using Microsoft.Extensions.Options;
using Delivery_app.web.Services;
using NToastNotify;
using Delivery_app.web.Models;
using AutoMapper;

namespace Delivery_app.web.Controllers
{
    public class CourierController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IEmailService _emailService;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;
        private readonly MailSettings _mailSettings;
        private Random random = new Random();

        public CourierController(AppDbContext context, 
            IOptions<MailSettings> mailSettings, 
            IEmailService emailService,
            IMapper mapper,
            IToastNotification toastNotification)
        {
            _context = context;
            _emailService = emailService;
            _mapper = mapper;
            _toastNotification = toastNotification;
            _mailSettings = mailSettings.Value;
        }

        public async Task<IActionResult> Index([FromQuery] string status, string searchQuery)
        {
            List<CourierViewModel> CouriersList;

            if (status == "pending")
            {
                CouriersList = await _context.couriers
                .Where(c => c.otp == null)
                .Select(c =>
                    new CourierViewModel
                    {
                        courier_id = c.courier_id,
                        profile_picture = c.profile_picture,
                        name = c.name,
                        email = c.email,
                        phone_num = c.phone_num,
                        vehicle_plate_no = c.vehicle_plate_no,
                        vehicle_type = c.vehicle_type,
                        documents = c.documents,
                        created_at = c.created_at,
                        updated_at = c.updated_at,
                        disable = c.disable,
                        commission = c.commission,
                        isRegistered = false
                    }
                ).ToListAsync();
            }
            else
            {
                CouriersList = await _context.couriers
                .Where(c => c.otp != null)
                .Select(c =>
                    new CourierViewModel
                    {
                        courier_id = c.courier_id,
                        profile_picture = c.profile_picture,
                        name = c.name,
                        email = c.email,
                        phone_num = c.phone_num,
                        vehicle_plate_no = c.vehicle_plate_no,
                        vehicle_type = c.vehicle_type,
                        documents = c.documents,
                        created_at = c.created_at,
                        updated_at = c.updated_at,
                        disable = c.disable,
                        commission = c.commission,
                        isRegistered = true
                    }
                ).ToListAsync();
            }

            if (!String.IsNullOrEmpty(searchQuery))
            {
                CouriersList = CouriersList.Where(c =>
                    c.name.Contains(searchQuery)
                    || c.email.Contains(searchQuery)
                    || c.vehicle_plate_no.Contains(searchQuery)
                    ).ToList();
            }

            return View(CouriersList);
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var courier = await _context.couriers.FindAsync(id);

                if(courier == null)
                {
                    _toastNotification.AddErrorToastMessage($"Failed to fetch edit courier.");
                    return RedirectToAction("Index");
                }

                var courierViewModel = _mapper.Map<CourierViewModel>(courier);

                return View(courierViewModel);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage($"Error occured, try again later.");
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CourierViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (id != model.courier_id)
            {
                ModelState.AddModelError("courier_id", "Id is not the same");
                return View(model);
            }

            var courier = await _context.couriers.FindAsync(id);

            if (courier == null)
            {
                _toastNotification.AddErrorToastMessage($"Failed to edit.");
                return View(model);
            }

            var editCourier = _mapper.Map<Couriers>(model);

            // update fields
            courier.name = editCourier.name;
            courier.phone_num = editCourier.phone_num;
            courier.email = editCourier.email;
            courier.vehicle_plate_no = editCourier.vehicle_plate_no;
            courier.vehicle_type = editCourier.vehicle_type;
            courier.commission = editCourier.commission;
            courier.disable = editCourier.disable;
            courier.updated_at = DateTime.Now;

            _context.couriers.Update(courier);

            await _context.SaveChangesAsync();

            _toastNotification.AddInfoToastMessage("Edited successfully.");

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AcceptRegistration(int id)
        {
            try
            {
                var courier = await _context.couriers.FindAsync(id);

                if (courier == null)
                {
                    _toastNotification.AddErrorToastMessage("Courier no found.");
                    return RedirectToAction("Index");
                }

                if (courier.otp != null)
                {
                    _toastNotification.AddErrorToastMessage("Courier registration already accepted.");
                    return RedirectToAction("Index");
                }

                var otp = this.RandomString(6);

                var toEmail = new List<String>
                {
                    courier.email
                };

                await _emailService.SendEmailAsync(
                    "Dear Applicant",
                    toEmail,
                    "Your Couriers Registration have been Approved",
                    "Your couriers registration on Delivery App have been approved.<br/>" +
                    "kindly login into with the following otp (one time password),<br/>" +
                    $"<h2>{otp}</h2><br/>" +
                    "you be able to change your password afterward successful login in."
                );

                courier.otp = otp;
                _context.couriers.Update(courier);

                await _context.SaveChangesAsync();

                _toastNotification.AddInfoToastMessage("Courier registration approved.");

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage($"Error occured, try again later.");
                return RedirectToAction("Index");
            }

        }

        private string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}

Delivery_app.web/Views/Courier/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit courier";
}
@model CourierViewModel

<div class="pb-3 pt-3">
    <a asp-controller="Courier" asp-action="Index" class="text-decoration-none text-dark d-flex justify-content-start align-items-baseline">
        <i class="fas fa-chevron-left fa-sm"></i>
        <h6 class="pl-2">Back</h6>
    </a>
    <h3 class="pt-2 pl-2">Edit Courier</h3>
</div>

<div class="px-2 pb-3">
    <form asp-action="Edit" method="post">
        <div class="custom-control custom-switch pb-3">
            <input asp-for="@Model.disable" type="checkbox" class="custom-control-input" id="switch">
            <label class="custom-control-label" for="switch">Disable account</label>
            <span asp-validation-for="@Model.disable" class="text-danger small font-italic"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="@Model.courier_id" />
            <span asp-validation-for="@Model.courier_id" class="text-danger small font-italic"></span>
        </div>
        <div class="form-row pb-2">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Name</label>
                    <input asp-for="@Model.name" type="text" class="form-control" placeholder="Name">
                    <span asp-validation-for="@Model.name" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Phone Num</label>
                    <input asp-for="@Model.phone_num" type="number" class="form-control" placeholder="Phone Num">
                    <span asp-validation-for="@Model.phone_num" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Email</label>
                    <input asp-for="@Model.email" type="email" class="form-control" placeholder="Email">
                    <span asp-validation-for="@Model.email" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Vehicle Type</label>
                    <select class="form-control" asp-for="@Model.vehicle_type" asp-items="@Html.GetEnumSelectList<VehicleType>()">
                    </select>
                    <span asp-validation-for="@Model.vehicle_type" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div class="form-row pb-2">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Vehicle Plate No.</label>
                    <input asp-for="@Model.vehicle_plate_no" type="text" class="form-control" placeholder="Vehicle Plate No.">
                    <span asp-validation-for="@Model.vehicle_plate_no" class="text-danger small font-italic"></span>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Commission</label>
                    <input asp-for="@Model.commission" type="number" class="form-control" placeholder="Commission(%)" min="0" max="1" step="0.1">
                    <span asp-validation-for="@Model.commission" class="text-danger small font-italic"></span>
                </div>
            </div>
        </div>
        <div>
            <input class="btn btn-info" type="submit" name="Edit" value="Edit" />
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(function () {
            $("#CouriersLink").removeClass("text-dark");
            $("#CouriersLink").addClass("text-danger");
        });
    </script>
}

Delivery_app.web/Views/Courier/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Couriers";
}
@model IEnumerable<CourierViewModel>

<div class="pb-3">
    <h3>Couriers</h3>
</div>
<div class="d-flex justify-content-between pb-3 flex-column flex-sm-row">
    <div>
        @if (Model.Count() != 0)
        {
        <a asp-controller="Courier" asp-action="Index" class="btn @((Model.First().isRegistered) ? "btn-danger" : "btn-outline-secondary")">All</a>
        <a asp-controller="Courier" asp-action="Index" asp-route-status="pending" class="btn @((Model.First().isRegistered) ? "btn-outline-secondary" : "btn-danger")">Pending</a>
        }
    </div>
    <form asp-controller="Courier" asp-action="Index" class="shadow-none shadow-sm pt-3 pt-sm-0">
        <div class="input-group col-3 col-sm-12 px-0">
            <input class="form-control" type="search" name="searchQuery" placeholder="Search.." aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-info" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>

<div>
    <div class="table-responsive table-bordered text-center">
        <table class="table table-striped table-hover">
            <thead class="">
                <tr>
                    <th>#</th>
                    <th>Profile</th>
                    <th>Name</th>
                    <th>Phone Num</th>
                    <th>Email</th>
                    <th>Vehicle Type</th>
                    <th>Vehicle Plate No</th>
                    <th>Documents</th>
                    <th>Created At</th>
                    <th>Commission(%)</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Count() != 0)
                {
                    @foreach (var d in Model)
                    {
                        if (d != null)
                        { 
                            <tr>
                                <td>@d.courier_id</td>
                                <td>
                                    <img class="img-fluid" width="55" src="http://localhost:57934/uploads/profile/@d.profile_picture">
                                </td>
                                <td>@d.name</td>
                                <td>@d.phone_num</td>
                                <td>@d.email</td>
                                <td>@d.vehicle_type.GetDisplayName()</td>
                                <td>@d.vehicle_plate_no</td>
                                <td>
                                    @foreach (var dd in d.documents)
                                    {
                                        <a href="http://localhost:57934/uploads/document/@dd.document" target="_blank">@dd.name</a>
                                        <br />
                                    }
                                </td>
                                <td>@d.created_at</td>
                                <td>@d.commission</td>
                                <td>
                                    <div class="custom-control custom-switch">
                                        <input disabled type="checkbox" class="custom-control-input" checked="@(!d.disable)">
                                        <label class="custom-control-label"></label>
                                    </div>
                                </td>
                                <td>
                                    @if (!d.isRegistered)
                                    {
                                        <a asp-controller="Courier" asp-action="AcceptRegistration" asp-route-id="@d.courier_id" class="btn btn-info btn-sm">Accept Registration</a>
                                    }
                                    else
                                    {
                                        <a asp-controller="Courier" asp-action="Edit" asp-route-id="@d.courier_id" class="btn btn-info btn-sm">Edit</a>
                                    }
                                </td>
                            </tr>
                        }
                    }
                }
                else
                {
                    <tr>
                        No record found.
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script>
        $(function () {
            $("#CouriersLink").removeClass("text-dark");
            $("#CouriersLink").addClass("text-danger");
        });
    </script>
}